# Site settings
title: Oooit
email: info@oooit.com
phone: (+31) 6 46 14 35 38
description: > # this means to ignore newlines until "baseurl:"
  Oooit Art was established in the Netherlands in January 2007 to support auspicious visual artists;
  to promote art and cultural exchange between countries;
  to assist art collectors and art lovers in finding their way in the international art world.
keywords: "research, financial supporting, recommendation, art exhibitions co-organization, art publishing services"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.oooit.com" # the base hostname & protocol for your site

mailer_url: "http://mailer.jinminjie.com/message"

# Build settings
markdown: kramdown
